### ISSUE TITLE
Handling exception in non determinstic transitions

### ISSUE THREAD

**Issue by lupaelma** [statefulj/statefulj#10]
When using non deterministic transition it is likely that exceptions may be raised. Can you update the Transition.getStateActionPair() interface to throw Exception? Or can you suggest how to work around this and handle errors in transitions?

**Comment by developer-x** [comment]
A checked exception typically implies a recoverable situation or in my estimation provides documentation to the client of the method of expected issues that the client should code for (eg. IOException when making network calls).

Since there isn't really any expected errors to occur when call getStateActionPair and since that really isn't a recoverable situation, then I would be reluctant to add a checked Exception - especially the root Exception as that conveys nothing in particular other than "some kind of" error can happen.

I think in your case, you will want to throw a RuntimeException since I'm assuming that this is an unexpected and non-recoverable error that you are throwing.

If I'm missing something, please let me know more detail about the error condition that you have.

**Comment by developer-x** [comment]
After some more consideration - I could add RetryException to the interface.  That tells the FSM that an error occurred but that the FSM should handle this exception and reprocess the event.  This exception is already part of the Action.execute method - so I do think adding it to the getStateAction method also makes sense.

So - you would then have two options - if you encounter an error and want to reprocess - throw a RetryException (or a WaitAndRetryException) or if you want the whole processing to stop - a RuntimeException.

Would this solve your problem?

**Comment by lupaelma** [comment]
Yes, this would help... thank you!

**Comment by developer-x** [comment]
I've pushed out a new release - 1.0.12 which has the updated Transition - let me know if this works
