### ISSUE TITLE
Domain objects populated from MyBatis SQL doesn't get @FSM injected

### ISSUE THREAD

**Issue by maceopark** [statefulj/statefulj#18]
I'm populating Account object with MyBatis and it has following events, states and transitions. (not fully defined) The issue I'm having is that after MyBatis mapper returns the object, @FSM doesn't work. fsm property is still null after object population. Could you share some insights on this please? Thanks.

```java
@StatefulController(
	value = BEAN_ID, clazz = Account.class, startState = Account.STATE_ACTIVE
)
public class Account extends DomainEntity<Account> {
	public final static String BEAN_ID = "Account";

	// States
	public static final String STATE_ACTIVE = "1";
	public static final String STATE_BANNED = "2";
	public static final String STATE_CANCEL_REQUESTED = "3";
	public static final String STATE_SEGREGATED = "4";

	// Internal Events
	final static String EVENT_BAN = "ban";
	final static String EVENT_SEGREGATE = "segregate";

	@FSM(BEAN_ID)
	StatefulFSM<Account> fsm;

	@State
	String state;

	private AccountOption accountOption;

	public void ban() {
		onEvent(EVENT_BAN);
	}

	@Transition(from= STATE_ACTIVE, event= EVENT_BAN, to= STATE_BANNED)
	protected void doBan() {
		setAccountFlag(AccountFlagsEnum.BAN, true);
		setState(STATE_BANNED);
	}

	@Override
	protected StatefulFSM<Account> getFSM() {
		return this.fsm;
	}

    (...)
}

**Comment by developer-x** [comment]
Can you provide some logging from the startup of the app?  I have logging that shows what SJ discovers and some debugging around the wiring - that would be the first place to start.

**Comment by developer-x** [comment]
Also, are you using Spring Data with MyBatis?  SJ supports Spring Data and JPA - so I'm not exactly sure how you have things set up - but SJ may not support your setup as-is.

**Comment by developer-x** [comment]
The issue is that in my demos, I use the StatefulJ framework to load the entities (via the binder endpoints).  The StatefulJ framework invokes Spring's autowireBeanProperties to wire the entity.  If you aren't using StatefulJ to load the entities, then you will need alternate way to access the FSM.

What I typically do in this case is create a Singleton object which instantiated by Spring, which has the FSM injected.  Then access the FSM from the non-Spring instantiated object via the Singleton method.
