### ISSUE TITLE
Retry Mechanism

### ISSUE THREAD

**Issue by kramer** [statefulj/statefulj#20]
Assuming I have a simple transition with an action like:

```
StateA  ---[ActionX]--->  StateB
``` 

If we are in `StateA` and `ActionX` throws a `RetryException` then the FSM will still move to `StateB` and will not actually call the `ActionX` again. This seems to be due to `setCurrent` call being before the `executeAction` call in [`FSM.transition` method](https://github.com/statefulj/statefulj/blob/master/statefulj-fsm/src/main/java/org/statefulj/fsm/FSM.java#L603).

Did I get the intention of the retry mechanism wrong or is that a bug?

**Comment by developer-x** [comment]
It does work the way you described and it is not a bug.  

Given the nature of Actions being potentially long running - only the transition is atomic.  Throwing a RetryException from an Action will not roll back the transition - simply reapply the event.  

In your case, I would recommend designing the FSM so the initial receipt of the event doesn't actually cause a state change - just simply invokes the action.  At the successful completion of the action, have the Action apply a "ActionSuccessful" event to the FSM to actually cause the transition on completion of the action.  That way, a RetryException thrown from Action will work the way you want.

**Comment by kramer** [comment]
Thanks for the clarification @developer-x . I just have a follow up question since you mentioned that "Actions can potentially be long running":

Assume the FSM:

```
StateA  ---[ActionX]--->  StateB  ---[ActionY]--->  StateC
``` 

If both actions are time consuming (or long running) and ActionY depends on ActionX's completion; then does that mean ActionY will fail if I don't put myself any checks to confirm ActionX was completed (i.e.: FSM fires actions completely async)?

**Comment by developer-x** [comment]
Actions are called synchronously; however, nothing restricts the action from delegating the functionality to a separate thread, message queue or other asynchronous process.  Additionally, StatefulJ can work with a number of data stores, some of which do not implement transaction support (e.g. Mongo).

But even if all the stores implemented transaction support - I still wouldn't try to make the transition/action transactional.  The reason is that you should MODEL your transactions using the FSM.  What I mean by that is you can do the following:

```
<Idle> -- event_A/Start Action --> <Action Pending> --- event_A/Wait, throw Retry Exception 
 ^                                      +
 |                                      |
 |                                      +----> action_Successful/NOOP --> <Done> -- event_A/NOOP --> <Done>
 |                                      |
 +--------------- action_Failed/NOOP -- +
```

So your Action code would look something like this:

```
public class FooAction<T> implements Action<T> {
	
	private FSM fsm;

	public FooAction(FSM fsm) {
		this.fsm = fsm;
	}
	
	@Override
	public void execute(T obj, String event, Object... args) throws RetryException {
		try {
			// .... perform your action
			this.fsm.onEvent(obj, "action_Success");
		} catch (Throwable t) {
			this.fsm.onEvent(obj, "action_Failed");
		}
	}

}
```
For your retry, you can just repurpose the provided WaitAndRetryAction https://github.com/statefulj/statefulj/blob/master/statefulj-fsm/src/main/java/org/statefulj/fsm/model/impl/WaitAndRetryActionImpl.java

**Comment by kramer** [comment]
Got it, thanks for the clarification! 🙇
